### ISSUE TITLE
Sense and scale flow sensors (2x)

### ISSUE THREAD

**Issue by lee-matthews** [RespiraWorks/VentilatorSoftware#100]
Read flow sensor voltages
Apply calibration data to scale measured voltages into SI units

**Comment by verityRF** [comment]
I worked on this (pending some breakages with platformIO that I'm in process of fixing). Is there something I'm missing or should this be considered closed?
PR #74

**Comment by jlebar** [comment]
I think this is done.  @verityRF are you interested in fixing https://github.com/RespiraWorks/VentilatorSoftware/issues/101?  I think this is a simple matter of plugging these two things together, but I am not 100% sure.
