### ISSUE TITLE
Create a controller module framework for PRVC and ACV ventilator modes

### ISSUE THREAD

**Issue by lee-matthews** [RespiraWorks/VentilatorSoftware#103]
Produce a respiration cycle controller module that abstracts the two operating modes (PRVC and ACV). Each operating mode shall be represented by its own module, each containing its associated FSM.

**Comment by jlebar** [comment]
Since alpha only has one ventilator mode, this doesn't block alpha.

**Comment by jkff** [comment]
This has been completed by @jlebar's nested FSM stuff yesterday.
