### ISSUE TITLE
Enforce clang-format formatting

### ISSUE THREAD

**Issue by jkff** [RespiraWorks/VentilatorSoftware#116]
Currently we advise people to install the precommit in https://github.com/RespiraWorks/VentilatorSoftware#developing, however if they don't, it's not enforced - people can still break formatting.

Ideally we would have a check in `.travis.yml` that verifies that code is correctly formatted with clang-format.

One example of how to do this is in https://github.com/mloskot/nanodbc/commit/5dc4e82f279fa6751f941e19adcabc7a679d8022 , where it is copied from a more complex project with a variety of checks at https://github.com/Project-OSRM/osrm-backend .

**Comment by jlebar** [comment]
@sienna0127 I think this is done?
