### ISSUE TITLE
Setup PlatformIO to target STM32L452 via Nucleo L452RE

### ISSUE THREAD

**Issue by hhff** [RespiraWorks/VentilatorSoftware#138]

**Comment by jlebar** [comment]
cc @khuey who was looking at qemu support for this device

**Comment by khuey** [comment]
Setting up platform.io to compile for a native device seems pretty easy, it's already supported there. Mostly just have to reconfigure the ini file and replace the existing AVR specific stuff (like the watchdog timer) that the controller uses.

Setting up a qemu emulation of the device would require some work.
