### ISSUE TITLE
PID variables in EEPROM

### ISSUE THREAD

**Issue by neelfirst** [RespiraWorks/VentilatorSoftware#15]
Copied thread from inceptionev/FixMoreLungs

@rwilbur We will need the variables to be stored in EEPROM so that in case of a reboot we still have the correct values for the variables

@lee-matthews Indeed, this functionality shall be provided by the eeprom module in the software.

**Comment by martukas** [comment]
Is this deserving to be in alpha? This is a safety feature in case of reboot, but is it crucial for functioning prototype? Same applies to #56 and #58

**Comment by lee-matthews** [comment]
I think we can move this to beta. We can just store these values as constants in flash for the time being.

**Comment by jlebar** [comment]
Dupe of https://github.com/RespiraWorks/VentilatorSoftware/issues/56
