### ISSUE TITLE
Implement watchdog timer

### ISSUE THREAD

**Issue by neelfirst** [RespiraWorks/VentilatorSoftware#16]
Copied thread from inceptionev/FixMoreLungs

@rwilbur We will need the watchdog timer so that we can make sure to reboot if something gets frozen

@lee-matthews In progress!, I've added the framework for this to the new ventilatorController branch

**Comment by martukas** [comment]
Is this still in a branch or is it done? I don't see commits referencing this.

**Comment by lee-matthews** [comment]
There is currently basic watchdog functionality that is working in the code.
