### ISSUE TITLE
Software Numerical Integration Routine

### ISSUE THREAD

**Issue by verityRF** [RespiraWorks/VentilatorSoftware#169]
We need to be able to report total air volume to the GUI computer. Sensors produce volumetric flow rate data. Thus, we need a software integrator to take the volumetric flow and integrate it w.r.t. time to get total volume.

**Comment by jkff** [comment]
TODO(@jkff) Link this to the GUI issues about displaying TV.

**Comment by martukas** [comment]
@jlebar saw some comments from you on slack implying we already had TV calculation implemented? Does this effectively close this issue?

**Comment by jlebar** [comment]
No.  It's not checked in, and what I have in my tree doesn't work well
enough for Alpha.

**Comment by martukas** [comment]
This issue blocks #10 and #229

**Comment by jlebar** [comment]
Forward-duping to #229.
