### ISSUE TITLE
Copy external PID library into our source, and make it compatible with HAL

### ISSUE THREAD

**Issue by jlebar** [RespiraWorks/VentilatorSoftware#174]
We currently use this external library for PID control, https://github.com/br3ttb/Arduino-PID-Library

This library is Arduino-specific -- in particular, it calls `millis()`.  An unfortunate side-effect of this is that no code of ours which uses this library can be unit-tested at the moment, because our unit tests need all Arduino calls to be mocked by HAL.

I think we should copy this library into our code and modify it to call Hal.millis() instead.  This is allowable because the other library is MIT-licensed; we just need to preserve the license header (which, interestingly, is sort of misapplied in the main fork).

Rough breakdown of tasks here:

1. Rename `controller/src/pid.{cpp.h}` to something else so they don't conflict with what we're about to do.  Maybe `control`?
1. Copy the code into e.g. `controller/libs/pid`, adding license headers and a note of the exact git hash we copied.
1. Commit the code without any other modifications (including without clang-format, which will be automatically applied if you have pre-commit installed, so commit with `SKIP=clang-format git commit`).
1. Run clang-format over the code, and commit that.
1. Replace `millis()` with `Hal.millis()`, and replace any other Arduino calls.  Remove Arduino.h include.  Commit this.
1. Now we should be able to move controller/src/control.{cpp.h} or whatever you called it into controller/lib/core, which will allow testing!  Yay.

**Comment by asmodai27** [comment]
Done inside https://github.com/RespiraWorks/VentilatorSoftware/pull/172
