### ISSUE TITLE
`test.sh` isn't safe to run locally

### ISSUE THREAD

**Issue by jlebar** [RespiraWorks/VentilatorSoftware#179]
`test.sh` is documented as a tool we can run locally, and also as a script that runs in Travis.

I think recent changes make it unsafe to run locally, however.  It tries to read `TRAVIS_BRANCH` and does things like `git reset --soft`.

cc @sienna0127

**Comment by jkff** [comment]
Obsolete after @sienna0127 's recent changes that put travis-only stuff in a separate script.
