### ISSUE TITLE
test.sh picks wrong base branch in CI

### ISSUE THREAD

**Issue by jlebar** [RespiraWorks/VentilatorSoftware#184]
@sienna0127, it seems that your good deed is not going unpunished.  :(

https://github.com/RespiraWorks/VentilatorSoftware/pull/172 ran  the following Travis build: https://travis-ci.com/github/RespiraWorks/VentilatorSoftware/builds/162117852

This fails because it's trying to do `git diff --name-only jlebar/ycm...HEAD`, and the `jlebar/ycm` branch no  longer exists.

I'm not sure exactly what's going on.  It sort of seems that Travis has gotten confused by the fact that this PR is part of a chain.  `jlebar/ycm` was the first link in this chain, and #172 depended on it.  Up until I submitted `jlebar/ycm`, Travis was right to consider only `jlebar/ycm...HEAD`.  But now that it's submitted, it should be looking at `master` as the base.

**Comment by hhff** [comment]
Fixed by #176
