### ISSUE TITLE
Tune PID parameters

### ISSUE THREAD

**Issue by jkff** [RespiraWorks/VentilatorSoftware#207]
**What has to be done**
The PID algorithm has three constants which control its behavior.  These live in `blower_pid.cpp` and need to be tuned so that the blower functions properly.

Our PID library has a fourth parameter; namely, the frequency with which we update the output.  Currently this is set to 100ms, but that's probably very high.

**How do you know it has to be done**
When you run the blower, it does not follow the setpoint.  Also I've been touching this code.

**Code pointers**
`blower_pid.cpp`

**Comment by jlebar** [comment]
Fixed by https://github.com/RespiraWorks/VentilatorSoftware/commit/c5dcac91dc05014e8e7829f14ee974830800fc21
