### ISSUE TITLE
Compute tidal volume in controller

### ISSUE THREAD

**Issue by jlebar** [RespiraWorks/VentilatorSoftware#214]
**What has to be done**
The controller needs to send three sensor-derived values to the GUI: patient pressure, volumetric flow, and tidal volume.  Right now we're only sending the first two; the third we set to 0.

This is a "very nice to have" for alpha.

**How do you know it has to be done**
Code inspection.

**Code pointers**
`sensors.cpp`

**Comment by martukas** [comment]
How does this relate to #169 ?

**Comment by jlebar** [comment]
Forward duped #169 here.
