### ISSUE TITLE
Connect graphs and information readout to real values

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/VentilatorSoftware#22]

**Comment by martukas** [comment]
blocked by #18 and #4

**Comment by martukas** [comment]
Possibly also blocked by #6 #8 #9

**Comment by neelfirst** [comment]
https://github.com/RespiraWorks/VentilatorSoftware/wiki/Alpha-milestone has been updated with more specific guidance for what is needed by 5/1. I have thus assigned priority label for #4 #6 #8 #22.

**Comment by jkff** [comment]
Closing, as I believe this issue is fully covered by the union of #4, #6, #8, #9:
- #4 deals with the controller speaking the communication protocol at all (i.e. obtaining the "real values")
- #6 #8 #9 deal with displaying these values.
