### ISSUE TITLE
Pressure setpoint square wave is not always consistent when running on Arduino

### ISSUE THREAD

**Issue by jlebar** [RespiraWorks/VentilatorSoftware#224]
Follow the instructions below to chart a pressure setpoint graph from the Arduino.  This shows the system pressure the Arduino *wants* to achieve.

This chart should be a square wave with a consistent period.  But every once in a while, we "miss a beat" and the inhale or exhale is too short or long.  It's very obvious in the graph.  It happens periodically, and for me always happens first around t=300 in the graph:

![image](https://user-images.githubusercontent.com/150663/80830504-ecf7a380-8b9d-11ea-9350-d657db47fe74.png)

You don't need pressure sensors hooked up or anything; I've reproduced it with the Arduino alone.

- Build at d8020002bc43fc794bf59613c79cb506104455a0, running on an Arduino RF Nano.

- Enable NO_GUI_DEV_MODE by uncommenting this line https://github.com/RespiraWorks/VentilatorSoftware/blob/d8020002bc43fc794bf59613c79cb506104455a0/controller/src/main.cpp#L68

- Run on the device, pio run -t upload

- Immediately start capturing a pressure trace using the Arduino IDE (tools -> serial plotter).  Use 115200 baud.

**What is wrong**
Square wave should be consistent, but it's not; it sometimes exhales for too long (attached image above).

**How do you know it is wrong**
By definition command-pressure has a consistent pressure wave.

**Code pointers**
`blower_fsm.cpp`?

**Comment by jlebar** [comment]
I don't know what's happening here.  It's tempting to think that this is due to some operation taking way too long and hanging up the whole main loop.  But I don't think that's it; if it were, we wouldn't be receiving *any* data from the device.

Something else is wrong.

**Comment by jlebar** [comment]
Putting this in the alpha controller milestone because I think it would be pretty embarrassing for us to show a graph to UCSF or whoever if we can't even consistently breathe in and out with the right timings.

**Comment by martukas** [comment]
What are the units on the x-axis? How bad is the delay?

**Comment by jlebar** [comment]
One tick on the x-axis is 1/10s.  The square wave is one breath.  This is a highly significant delay.

**Comment by Miceuz** [comment]
I can't reproduce it on STM32. Might be related to some long-ish float calculation.

**Comment by jlebar** [comment]
Thanks for running that test, Albertas.  That's really useful.

> Might be related to some long-ish float calculation.

If the calculation were stuck, the whole main loop would be stuck, and we wouldn't receive any data for that period of time.  But we *do* receive  data, indicating that  the loop isn't stuck.

**Comment by jlebar** [comment]
Something is wrong with the timer.

In this chart, the orange line that's a step function is charting `Hal.now().millisSinceStartup() / 1000 % 10`.

![image](https://user-images.githubusercontent.com/150663/80917429-aaf06e00-8d13-11ea-8351-af1dcd978de1.png)

This next chart tracks both native Arduino `millis()` and `Hal.now().millisSinceStartup()`.  I am not sure which line is which, but I think it's the Hal line that's misbehaving.

![image](https://user-images.githubusercontent.com/150663/80917553-8f399780-8d14-11ea-8a1a-c82e221aa40d.png)

**Comment by jlebar** [comment]
Ah, this is 16-bit overflow in the hal timer.
