### ISSUE TITLE
Check PID gains are in tune with new PID

### ISSUE THREAD

**Issue by asmodai27** [RespiraWorks/VentilatorSoftware#248]
**What has to be done**
Some changes were made on the PID to make it more resilient to jitter and make the actual math more precise when jitter is added to the call period.

**How do you know it has to be done**
From controls (limited) experience (took two aeronautical controls classes at ERAU 10 years ago...): The PID gains' tuning is sensitive to sample time, and the changes brought by https://github.com/RespiraWorks/VentilatorSoftware/pull/221 change the effective sample time of the PID.

**Code pointers**
check previous tunings: https://github.com/RespiraWorks/VentilatorSoftware/pull/233
This requires having a physical hardware with test lung to perform closed loop tuning, or full closed loop model (which we don't have yet...)

**Comment by jlebar** [comment]
Verified it works fine; I can't distinguish between before and after this patch.
