### ISSUE TITLE
Implement inspiratory attempt detection

### ISSUE THREAD

**Issue by tapemaster** [RespiraWorks/VentilatorSoftware#374]
Depends on #373 

After investigation is done, this task is to code it.

**Comment by jkff** [comment]
Some sources on how to do this from Slack:
https://derangedphysiology.com/main/cicm-primary-exam/required-reading/respiratory-system/Chapter%20535/triggering-mechanically-supported-breath
https://respiraworks.slack.com/archives/C011CJQV4Q7/p1591330529182400 (links to https://link.springer.com/content/pdf/10.1007/BF02915533.pdf)

**Comment by asmodai27** [comment]
https://github.com/RespiraWorks/VentilatorSoftware/pull/468 and https://github.com/RespiraWorks/VentilatorSoftware/pull/548
