### ISSUE TITLE
Implement mode selection

### ISSUE THREAD

**Issue by tapemaster** [RespiraWorks/VentilatorSoftware#386]
We intend to support Command Pressure aka Mandatory Ventilation (device commands all breaths), Pressure Assist (device detects inhale effort and helps that breath, but also initiates breaths if patient doesn't), CPAP with O2 therapy aka HFNC (light constant positive O2-saturated air pressure, non-invasive).

Latest UI requirements are here: https://github.com/RespiraWorks/VentilatorSoftware/wiki/UI-Requirements

**Comment by jkff** [comment]
This is done: the GUI can select between the modes. Command Pressure and Pressure Assist are actually implemented, HFNC is not.
