### ISSUE TITLE
Implement pressure assist mode

### ISSUE THREAD

**Issue by tapemaster** [RespiraWorks/VentilatorSoftware#388]
We already have mandatory ventilation mode implemented in Alpha.
Pressure assist mode is a hybrid - it is triggering a mandatory ventilation when it detects inspiratory attempt (#374, #373). If inspiratory attempt was not detected during a long time <TODO: define a threshold>, we deliver a mandatory ventilation.

A breath cycle is defined by the control parameters below. The patient can exceed the respiratory rate by initiating additional breaths, but the breath parameters do not change.
Control parameters:
 - PIP. Peak Inspiratory Pressure.
 - PEEP. Positive End-Exhalatory Pressure.
 - FiO2. Fraction of Inspired Oxygen.
 - I-time. Inspiratory (rise + dwell) time.
 - Inspiratory sensitivity.
 - RR. Respiratory Rate.
Display parameters: PIP/PEEP/RR/FiO2/I-time.
Relevant Alarms: low/high tidal volume #369, High RR

Full description of ventilator modes is [here](https://github.com/RespiraWorks/VentilatorSoftware/wiki/Ventilator-modes). 

What also needs to be taken care of is to avoid breathstacking. We don't want to start another breath cycle before previous exhale didn't finish.

**Comment by asmodai27** [comment]
per https://github.com/RespiraWorks/VentilatorSoftware/pull/468

**Comment by asmodai27** [comment]
still some work to do on GUI side, https://github.com/RespiraWorks/VentilatorSoftware/pull/468 and https://github.com/RespiraWorks/VentilatorSoftware/pull/548 take care of this on controller side. Some tuning may be necessary for corner cases.
