### ISSUE TITLE
UX recommendations and design for Alarm Settings user flow

### ISSUE THREAD

**Issue by tapemaster** [RespiraWorks/VentilatorSoftware#396]
Before we add alarm settings to the GUI, we should do a research on how they should look and behave. Ideal outcome of this is a specifications for developers who will do coding part.

Useful links:
 - Old design: https://www.figma.com/file/Ci9thGhcOA3eVbZ6Uije0O/Ventilator-UI
 - UI requirements https://github.com/RespiraWorks/VentilatorSoftware/wiki/UI-Requirements
 - List of alarms we need for covent milestone https://github.com/RespiraWorks/VentilatorSoftware/milestone/11

**Comment by jkff** [comment]
This is done as part of https://github.com/RespiraWorks/VentilatorSoftware/issues/397.
