### ISSUE TITLE
Update PID loop to command oxygen input

### ISSUE THREAD

**Issue by tapemaster** [RespiraWorks/VentilatorSoftware#409]

**Comment by neelfirst** [comment]
This comes from https://respiraworks.slack.com/archives/CV84M1CKB/p1590835884056700

Where the PSOL (proportional solenoid for the oxygen line) is observed to require separate PID ctrl params from the pinch valves.

**Comment by jkff** [comment]
Slack discussion on how to implement this: https://respiraworks.slack.com/archives/C013KQQ18T1/p1590958437040000

**Comment by inceptionev** [comment]
I believe this can be closed, yes @tapemaster @jlebar ?
