### ISSUE TITLE
Add sensor code 

### ISSUE THREAD

**Issue by lee-matthews** [RespiraWorks/VentilatorSoftware#57]
- Add ability to read from flow and pressure sensors
- Get calibration data
- Apply calibration data
- Provide warnings if sensor failure detected

**Comment by martukas** [comment]
Could it be that this is duplicate and/or already broken down into smaller tasks in #35 #36 #38 #40 #41 #44 ?

**Comment by neelfirst** [comment]
I concur with @martukas , issues should be kept focused and small, so related PRs can be similarly small and reviewed quickly.

**Comment by neelfirst** [comment]
This also seems like controller specific code, rather than common code. I'm not sure the raspi has any business interfacing with sensors.

**Comment by martukas** [comment]
Blocked by #41 #40 #44

**Comment by lee-matthews** [comment]
Indeed, this code is destined to manage the sensors on the Arduino board.
