### ISSUE TITLE
GUI must display real-time graphs for Pressure, Flow

### ISSUE THREAD

**Issue by rwilbur** [RespiraWorks/VentilatorSoftware#6]
# Requirement
The UI must be able to display the pressure and calculated or measured flow rate in a graph format that updates in (near) real time

**Comment by martukas** [comment]
Is this not already done, albeit with spoofed values?

**Comment by martukas** [comment]
This possibly blocks #22

**Comment by neelfirst** [comment]
https://github.com/RespiraWorks/VentilatorSoftware/wiki/Alpha-milestone has been updated with more specific guidance for what is needed by 5/1. I have thus assigned priority label for #4 #6 #8 #22.

**Comment by jkff** [comment]
This is not done. This issue must build on https://github.com/RespiraWorks/VentilatorSoftware/issues/4 and involves:

- Having UI elements with these graphs (yes, we have that already)
- Binding data in these graphs to data obtained via the communication protocol (we don't have this)

**Comment by jlebar** [comment]
Edited this bug to focus on just pressure and flow, these are the two that we're confident we need.

TODO @jlebar follow up whether we need tidal volume as a hard requirement for alpha.

**Comment by jlebar** [comment]
From Ethan, TV is in the "very nice to have" camp.

**Comment by neelfirst** [comment]
For TV - may be an unnecessary hack, but since we're only doing pressure command, can we just reset to zero every time?
