### ISSUE TITLE
OXY: determine control values for VentilatorSoftware for v0.2 (CoVent demo hardware)

### ISSUE THREAD

**Issue by inceptionev** [RespiraWorks/VentilatorSoftware#613]
same as RespiraWorks/SystemDesign#136, but for the oxygen PSOL controller

- determine exhale valve PEEP setting (maximum position for achieving highest expected PEEP with inhale valve fully open)
- determine exhale valve PIP setting (minimum position for achieving lowest expected PIP with inhale valve fully closed))
- determine acceptable kp value
- determine acceptable ki value
- run test case and post data

note that these values are being selected for highest performance, not lowest gas consumption. Once these values have been established, they can be tuned for other cost functions.

**Comment by martukas** [comment]
@inceptionev do we consider this done?

**Comment by inceptionev** [comment]
Done!

**Comment by inceptionev** [comment]
closing issue, completed by b514f94b0de66710a43f8e3bb138cbb976c54fca
