### ISSUE TITLE
Generate IDE-independent makefile for controller

### ISSUE THREAD

**Issue by neelfirst** [RespiraWorks/VentilatorSoftware#65]

**Comment by jlebar** [comment]
I'm going to call this done, since we have command-line build instructions for building and testing with platformio.

**Comment by neelfirst** [comment]
Link to file? Or simple one-liner? For posterity. Thanks.

**Comment by jlebar** [comment]
README.md

**Comment by neelfirst** [comment]
Ok thanks.

https://github.com/RespiraWorks/VentilatorSoftware/blob/master/README.md#ventilatorsoftware
