### ISSUE TITLE
Optimize checksum code and write tests

### ISSUE THREAD

**Issue by jlebar** [RespiraWorks/VentilatorSoftware#66]
I think the checksuming code can be improved somewhat: https://gcc.godbolt.org/z/cHmBLE.

More than this likely-unimportant optimization, I want to use this as an excuse to write tests and set up testing infrastructure.

**Comment by jlebar** [comment]
There's also some refactoring to do, as part of the logic of `checksum_check` is duplicated in `serialIO.cpp`.

**Comment by jlebar** [comment]
See also https://en.wikipedia.org/wiki/Fletcher%27s_checksum#Optimizations

**Comment by martukas** [comment]
Is this urgent enough to be in alpha?

**Comment by jlebar** [comment]
Unit tests and testing infrastructure is highly urgent, yes!

**Comment by martukas** [comment]
Yes, unit testing is urgent, I agree :) I was more questioning the urgency of optimization. But all is good.
