### ISSUE TITLE
Spec out sw dev care package

### ISSUE THREAD

**Issue by neelfirst** [RespiraWorks/VentilatorSoftware#695]
Create with part numbers and links a package to essential kit a developer needs to move forward with testing against hardware.

Bare essential dev kit
- nucleo-L452RE
- raspi 3b+
- touchscreen
- hdmi cable
- uUSB2 cable x3
- jumpers for UART

Possibly a sensors package?
- 3x MPXV5000
- some 2.5mm tubing
- STEP files for venturi tubes
- instructions for wiring

**Comment by VSTheBestDeveloper** [comment]
This ticket was in the "Done" column in Hardware. Moved it to the same column after changing repositories.

**Comment by martukas** [comment]
This is actually now fully documented here:
https://github.com/RespiraWorks/Ventilator/tree/master/manufacturing/brain
