### ISSUE TITLE
Display ventilation mode

### ISSUE THREAD

**Issue by rwilbur** [RespiraWorks/VentilatorSoftware#7]
# Requirement
The UI must display what ventilation is currently being used, including a clear method of showing that the unit is off

**Comment by ianballou** [comment]
In my learning about how ventilators work, it seems like there isn't a solid definition of what a mode has to be, and they can be mixed.  AC can have PEEP, AC can be volume or pressure control, etc.

Is there a chart available for the modes we are supporting?  Similarly, will there need to be sub-modes, like AC-Volume or AC-Pressure?

**Comment by ianballou** [comment]
Fixed in #73
