### ISSUE TITLE
Inspect micro SD card choice. Do we need more than a UHS-1 Class 10, e.g. Pro Endurance or similar.

### ISSUE THREAD

**Issue by neelfirst** [RespiraWorks/VentilatorSoftware#700]
@neelfirst key specs are UHS-1 Class 10.
@rwilbur We may want to see if we can use a high endurance uSD card. Not sure how well it works with the Pi though.
@neelfirst e.g. https://www.crutchfield.com/S-HhCUE8KcYw9/p_305MJ32GA/Samsung-Pro-Endurance-microSDHC-Memory-Card-32GB.html
@rwilbur not sure how necessary it is. might be slower.
@neelfirst UHS-1 means it should be same speed, right?

**Comment by VSTheBestDeveloper** [comment]
This ticket was in the "Done" column in Hardware. Moved it to the same column after changing repositories.
