### ISSUE TITLE
Test passive flow restriction valve

### ISSUE THREAD

**Issue by ebhillstrom** [RespiraWorks/VentilatorSoftware#701]
Related to issue RespiraWorks/VentilatorSoftware#655. Relevant comments:

https://github.com/RespiraWorks/PhysicalDesign/issues/11#issuecomment-614119995
https://github.com/RespiraWorks/PhysicalDesign/issues/11#issuecomment-614121020

This part is an alternative to an exhaust restriction solenoid, and is designed to minimize oxygen bypass and wastage. If effective it is much cheaper and saves supply chain lead time (could possibly be made in country of ventilator manufacture if tooling is available). However, it is a part that may need to be injection molded and which we will need to run qualification testing on ourselves to have design confidence.

**Comment by VSTheBestDeveloper** [comment]
This ticket was in the "Done" column in Hardware. Moved it to the same column after changing repositories.495eae3cb.png)
