### ISSUE TITLE
Find a source for inline medical filters, or change architecture

### ISSUE THREAD

**Issue by ebhillstrom** [RespiraWorks/VentilatorSoftware#702]
Find a widely available source for inline bacterial/viral filters like the following: https://www.cpap.com/productpage/Respironics-in-line-outlet-filter-bacteria-cpap-bipap-10-pack

...we need to make sure these will continue to be available given global supply chain stresses on filter media. If we can't guarantee this, we will fall back on the system inlet/outlet filter which means we need to re-evaluate the integrity of this filter.

**Comment by VSTheBestDeveloper** [comment]
This ticket was in the "Done" column in Hardware. Moved it to the same column after changing repositories.
