### ISSUE TITLE
Decide on patient tubing connection standard

### ISSUE THREAD

**Issue by ebhillstrom** [RespiraWorks/VentilatorSoftware#703]
Available dimensional standards: https://www.iso.org/obp/ui#iso:std:iso:5356:-1:ed-4:v1:en 15mm and 22mm are the two options in scope

Needs some research on common ventilator configurations and available breathing circuits on the market. The goal is to avoid cornering a hospital into needing to buy from a limited supply of breathing circuits. Note that the inspiratory connection should go to a humidifier, and _then_ to the patient, so the inspiratory connection should be compatible with a short hose that can jump to the humidifier inlet port - see issue RespiraWorks/SystemDesign#10.

**Comment by VSTheBestDeveloper** [comment]
This ticket was in the "Done" column in Hardware. Moved it to the same column after changing repositories.
