### ISSUE TITLE
Finalize flow measurement solution

### ISSUE THREAD

**Issue by neelfirst** [RespiraWorks/VentilatorSoftware#705]
The flow sensor was originally a pneumotachograph. However, the signal/noise ratio was too high and a venturi was selected as the next option. The venturi was 3D printed with a 0.5 in D and a 0.157 in throat. The venturi calculation spreadsheet is [visible here](https://docs.google.com/spreadsheets/d/1G9Kb-ImlluK8MOx-ce2rlHUBnTOtAFQvKjjs1bEhlpM/edit?usp=sharing). The major problem with venturi is concern over the results in one test, that may be more systemic. 
These results came from one test that @inceptionev ran where we were not able to distinguish the inflow and outflow on exhale. In the plot below, the Orange is the inflow and the purple is the outflow dP. The blue trace is the command pressure and orange trace is measured pressure.
![image (11)](https://user-images.githubusercontent.com/62855852/79355047-09cf7e00-7ef2-11ea-97f1-2683f3748de4.png)
When the solenoid opens, the lungs are deflating (observation) but the plot would indicate that more inflow than exflow means the lungs are deflating. We should plan another test to explore this phenomenon since the spreadsheet indicates what we tested is close to optimized.

**Comment by VSTheBestDeveloper** [comment]
This ticket was in the "Done" column in Hardware. Moved it to the same column after changing repositories.
