### ISSUE TITLE
Create solenoid control module

### ISSUE THREAD

**Issue by lee-matthews** [RespiraWorks/VentilatorSoftware#79]

**Comment by martukas** [comment]
@neelfirst @lee-matthews @jlebar  is this blocked by anything? Does any other feature need this?

**Comment by lee-matthews** [comment]
No. The control loop will need this to control the solenoid. I've coded the
module already, it's on GitHub.

**Comment by martukas** [comment]
Ah, ok. I see the branch.
It would be very helpful if you could tag your commits with the issue #, as suggested [here](https://github.com/RespiraWorks/VentilatorSoftware/wiki/Branch-naming-&-commit-messages), which will automatically update the ticket.

**Comment by lee-matthews** [comment]
That's useful. Thanks. I'll do that from now on.

**Comment by neelfirst** [comment]
Just so we're clear, the solenoid doesn't need any complex control, it is a simple digital I/O that feeds a FET driver to turn on/off.

**Comment by lee-matthews** [comment]
Exactly, the solenoid would be controlled from the ventilator control algo
that hasn't been done yet.

**Comment by jlebar** [comment]
solenoid.cpp exists.
