### ISSUE TITLE
GUI must display readouts (instantaneous values) of PEEP, PAW

### ISSUE THREAD

**Issue by rwilbur** [RespiraWorks/VentilatorSoftware#8]
# Requirement
Must have 3 readouts displaying Tidal Volume, Positive End-Expiratory Pressure, and airway pressure in numerical format

**Comment by martukas** [comment]
This possibly blocks #22

**Comment by twslankard** [comment]
@rwilbur I don't see a PAW readout on [this mockup](https://respiraworks.slack.com/files/U010ZMKPT7W/F012S13H072/ventilator_ui.pdf). Do you know if this is the latest version?

**Comment by neelfirst** [comment]
https://github.com/RespiraWorks/VentilatorSoftware/wiki/Alpha-milestone has been updated with more specific guidance for what is needed by 5/1. I have thus assigned priority label for #4 #6 #8 #22.

**Comment by jkff** [comment]
Decision (@neelfirst): just display instantaneous values of whatever is on the graphs.

**Comment by martukas** [comment]
Possibly blocked by #169
