### ISSUE TITLE
Setup Cross Platform Build & Test System for CI & Dev

### ISSUE THREAD

**Issue by hhff** [RespiraWorks/VentilatorSoftware#87]
Please take the time to describe the issue in detail, so that other contributors can pick it up and implement or declare it done/obsolete in case if was completed out of band.

**What has to be done**
- Ensure there's a (somewhat) unified way for both local dev & CI to build & test the project
- Given there is no unit testing in the GUI, we should add some basic boilerplate so that we have something to run

**Comment by twslankard** [comment]
@hhff anything I can help with here? (Or anything related?)
