### ISSUE TITLE
update license to apache v2

### ISSUE THREAD

**Issue by neelfirst** [RespiraWorks/VentilatorSoftware#92]

**Comment by neelfirst** [comment]
![consent_of_contributors](https://user-images.githubusercontent.com/560842/79374544-3ee8ca00-7f0c-11ea-84c9-1601919b2ff6.png)

**Comment by thekalinga** [comment]
May I know the reason for this license change?

**Comment by neelfirst** [comment]
See slack thread in https://github.com/RespiraWorks/VentilatorSoftware/pull/93

**Comment by thekalinga** [comment]
I tried accessing the url, but slack took me to login page where I am not allowed to login

Do new emails needs to registered as part of the org before others (like me) can see the chat?
